version: '3.7'

services:
  next:
    build:
      context: .
      target: dev
    container_name: next-app-dev
    image: next-app-dev
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./src/public:/app/public
      - next-node_modules:/app/node_modules
    tty: true
    ports:
      - "3000:3000"

volumes:
  next-node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
